# Generated by Django 3.2.5 on 2021-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Device_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='Device_Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='Room',
            field=models.CharField(default='', max_length=50),
        ),
    ]
