# Generated by Django 3.2.5 on 2022-01-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211209_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Todays_Bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='Total_Bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='Units',
            field=models.FloatField(default=0.0),
        ),
    ]
