# Generated by Django 3.2.5 on 2022-01-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220104_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='x',
            field=models.FloatField(default=0.0),
        ),
    ]
