# Generated by Django 3.2.5 on 2022-01-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_sensor_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='x',
        ),
    ]
