# Generated by Django 3.2.5 on 2022-01-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_sensor_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Todays_Bill',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='Total_Bill',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='Units',
        ),
    ]
