# Generated by Django 3.2.5 on 2022-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sensor_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='x',
            field=models.FloatField(),
        ),
    ]
