# Generated by Django 3.2.5 on 2022-01-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_sensor_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Todays_Bill',
        ),
    ]
