# Generated by Django 3.2.5 on 2022-01-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_sensor_todays_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Todays_Bill',
            field=models.FloatField(default=0.0),
        ),
    ]
