# Generated by Django 3.2.5 on 2022-01-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_sensor_todays_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='EB_Status',
        ),
    ]
