# Generated by Django 3.2.5 on 2022-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_sensor_eb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Door',
            field=models.BooleanField(default=True),
        ),
    ]
