# Generated by Django 3.2.5 on 2022-01-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20220106_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Door',
            field=models.BooleanField(default=False),
        ),
    ]
