# Generated by Django 3.2.5 on 2022-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_sensor_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='Temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
