# Generated by Django 3.2.5 on 2022-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20220209_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Door_Close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='Door_Open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='Door_Pause',
            field=models.BooleanField(default=False),
        ),
    ]
