# Generated by Django 3.2.8 on 2022-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20220323_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Door_Motor',
            field=models.BooleanField(default=False),
        ),
    ]
