# Generated by Django 3.2.8 on 2022-04-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_sensor_door_motor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Door',
        ),
    ]
