# Generated by Django 3.2.8 on 2022-04-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_sensor_door'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Door_Pause',
        ),
    ]
