# Generated by Django 3.2.8 on 2022-04-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_sensor_door_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Door_Pause',
            field=models.BooleanField(default=False),
        ),
    ]
