# Generated by Django 3.2.8 on 2022-06-18 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_sensor_motion_sensor_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Motion_sensor_Time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 18, 11, 34, 59, 800223)),
        ),
    ]
