# Generated by Django 3.2.8 on 2022-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_sensor_motion_sensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Motion_sensor_Time',
            field=models.TimeField(default='11:36:38'),
        ),
    ]
