# Generated by Django 3.2.8 on 2022-06-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_sensor_motion_sensor_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Motion_sensor_Time',
        ),
    ]
