# Generated by Django 3.2.8 on 2022-06-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_sensor_sensor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Name', models.CharField(max_length=50)),
                ('Device_State', models.BooleanField(default=False)),
                ('Device_Room', models.CharField(max_length=50)),
                ('Time', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
