# Generated by Django 3.2.8 on 2022-06-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='Off_State',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motion',
            name='On_State',
            field=models.BooleanField(default=False),
        ),
    ]
