# Generated by Django 3.2.8 on 2022-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20220624_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='Device_Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='motion',
            name='Device_Type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
