# Generated by Django 3.2.5 on 2022-08-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20220624_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Last_Updated',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='device',
            name='Time_Stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fan',
            name='Last_Updated',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='fan',
            name='Time_Stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motion',
            name='Last_Updated',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='motion',
            name='Time_Stamp',
            field=models.IntegerField(default=0),
        ),
    ]
