# Generated by Django 3.2.5 on 2022-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20220805_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Name', models.CharField(max_length=50)),
                ('Board_Room', models.CharField(max_length=50)),
                ('Device_IP', models.CharField(max_length=50)),
                ('Device_MAC', models.CharField(max_length=50)),
                ('Ping', models.CharField(max_length=50)),
                ('Time_Stamp', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heater_Name', models.CharField(max_length=50)),
                ('Heater_Room', models.CharField(max_length=50)),
                ('Heater_Status', models.BooleanField(default=False)),
                ('Device_Type', models.CharField(default='', max_length=50)),
                ('Device_IP', models.CharField(max_length=50)),
                ('Device_MAC', models.CharField(max_length=50)),
                ('Off_Time', models.CharField(max_length=50)),
                ('Ping', models.CharField(max_length=50)),
                ('Time_Stamp', models.IntegerField(default=0)),
                ('Last_Updated', models.CharField(default='', max_length=70)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='tab',
            name='Last_Updated',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tab',
            name='Time_Stamp',
            field=models.IntegerField(default=0),
        ),
    ]
