# Generated by Django 3.2.5 on 2022-08-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20220815_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Table',
            field=models.BooleanField(default=False),
        ),
    ]
