# Generated by Django 3.2.8 on 2022-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_sensor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Height', models.IntegerField(default=0)),
                ('Room', models.CharField(max_length=30)),
                ('Up', models.BooleanField(default=False)),
                ('Down', models.BooleanField(default=False)),
                ('Pause', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
