# Generated by Django 4.1 on 2022-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_auto_20220819_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onyx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Command', models.CharField(default='', max_length=50)),
                ('Sender', models.CharField(default='', max_length=50)),
                ('Receiver', models.CharField(default='', max_length=50)),
                ('Reply', models.CharField(default='', max_length=50)),
                ('Time_Stamp', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
