# Generated by Django 4.1.2 on 2022-11-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_onyx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Ping',
            new_name='Host_Name',
        ),
        migrations.AddField(
            model_name='board',
            name='Wifi_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
