# Generated by Django 4.1.1 on 2022-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_board_announced'),
    ]

    operations = [
        migrations.CreateModel(
            name='em',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField(default=0)),
                ('ampere', models.FloatField(default=0.0)),
                ('ups', models.IntegerField(default=0)),
                ('eb_status', models.BooleanField(default=False)),
                ('units', models.FloatField(default=0.0)),
                ('announced', models.BooleanField(default=False)),
                ('announcement_time', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('time_stamp', models.IntegerField(default=0)),
                ('motor_status', models.BooleanField(default=False)),
                ('announced', models.BooleanField(default=False)),
                ('announcement_time', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
