# Generated by Django 4.1.3 on 2022-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_em_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='led',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room', models.CharField(default='', max_length=50)),
                ('Name', models.CharField(default='', max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('RGB', models.IntegerField(default=0)),
                ('Hexa', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=False)),
                ('Time_Stamp', models.IntegerField(default=0)),
                ('Last_Updated', models.CharField(default='', max_length=70)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
