# Generated by Django 4.1.3 on 2022-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_led'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='Hexa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='led',
            name='RGB',
            field=models.CharField(default='', max_length=50),
        ),
    ]
