# Generated by Django 4.1.3 on 2022-11-30 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_led_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='Brightness',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
