# Generated by Django 4.1.3 on 2022-11-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_alter_led_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='Brightness',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
