# Generated by Django 4.1.3 on 2022-11-30 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_led_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='Brightness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
